### ISSUE TITLE
Coding conventions in NEXUS

### ISSUE THREAD

**Issue by jmunozv** [next-exp/nexus#1]
By Justo @ Gitlab (See discussion on [GitLab](https://next.ific.uv.es:8888/nextsw/nexus/issues/2)).

I have noticed a departure lately from the historical coding conventions that we had been following in NEXUS. Some examples include function names mixing CamelCase with underscores or function names using only underscores. We should, perhaps, write some conventions we can all agree with and start enforcing them during the revision of merge requests.

**Comment by paolafer** [comment]
The conventions are in NEXUS Wiki.
