### ISSUE TITLE
Implement the new Hamamatsu SiPMs (1.3 mm × 1.3 mm) that will be used in NEXT-100

### ISSUE THREAD

**Issue by jmunozv** [next-exp/nexus#13]
NEXT-100 will make use of new Hamamatsu SiPMs of $`1.3 \times 1.3~\mathrm{mm}^2`$ active area. Their geometry and optical properties have to be added to NEXUS.

Data-sheet with their description:
[K30-I50426_specification_sheet_S13372-1350TE_.pdf](/nextsw/nexus/uploads/a3b460fe1cef791de35eec14dbf5b0f1/K30-I50426_specification_sheet_S13372-1350TE_.pdf)

**Comment by paolafer** [comment]
Issue solved.
