### ISSUE TITLE
Random sampler of arbitrary binned distributions

### ISSUE THREAD

**Issue by jmunozv** [next-exp/nexus#14]
Several classes in NEXUS make use of ROOT histograms to sample randomly arbitrary binned functions. We should write our own function or class that provides this functionality in order to remove, as planned, the dependency on ROOT.

**Comment by paolafer** [comment]
The dependency on ROOT has been eliminated. We can still implement our own sampler, if we want to.

**Comment by paolafer** [comment]
The possibility of using a random distribution is being added in PR #171.

**Comment by paolafer** [comment]
PR #171 has been approved and merged.
