### ISSUE TITLE
Scintillation yield in the mesh volumes

### ISSUE THREAD

**Issue by jmunozv** [next-exp/nexus#18]
Since part of the volumes of the meshes (cathode, gate and anode) are in a region with an electric field defined, the `IonizationClustering` process occurs. This process expects scintillation optical properties, to generate scintillation photons related to the energy depositions. However, in order to simulate the scintillation correctly in the meshes, we would need to read the scintillation properties from the material they're made of (xenon gas), which is not the case in the current code. Alternatively, we could redefine the cathode, gate and anode positions to exclude these volume entirely.

The discussion is open.

**Comment by paolafer** [comment]
This issue is superseded in the case of stainless steel grids, which is now the default option, therefore I'll close it.
