### ISSUE TITLE
Random point samplers

### ISSUE THREAD

**Issue by jmunozv** [next-exp/nexus#2]
The random point sampling classes need a complete overhaul. A few issues that need to be addressed:

- The `G4String`-based interface is slow. Enums should be used instead.
- The names for the different regions should be unified.
- The geometric definition should probably follow those of the geometry classes. The point samplers could even take a logical/physical volume as input for construction.
- The muon point sampler does not belong there.
- Tests should be written.

The above list is not exhaustive, of course.

**Comment by paolafer** [comment]
Bullets 1, 2, 3, 4 and 5 are being addressed in PR #239.

**Comment by paolafer** [comment]
PR #239 solves this issue completely, I think.
