### ISSUE TITLE
Transparency of photo-etched meshes

### ISSUE THREAD

**Issue by jmunozv** [next-exp/nexus#4]
The photo-etched meshes that will be installed in NEXT-100 follow a honeycomb arrangement of 5-mm wide cells. Their quoted transparency is ~95%. We should check that our current optical model for the meshes (a dielectric with a certain absorption length) is still correct for these new meshes.

**Comment by kvjmistry** [comment]
This issue will be resolved in PR #187

**Comment by paolafer** [comment]
Solved by PR #187.
