### ISSUE TITLE
SetELzCoord and GetELzCoord functions from BaseGeometry

### ISSUE THREAD

**Issue by jmalbos** [next-exp/nexus#47]
These two functions are not general enough to be part of the base class `BaseGeometry`. On top of that, their use to position a physical volume within its mother results in somewhat obscure code, in my opinion. A simple alternative: providing the origin of coordinates via the constructor as done in the class `Next100TrackingPlane()`, or via a setter specific to the class that the user has to call necessarily.

**Comment by paolafer** [comment]
Yes, I agree.

**Comment by jmunozv** [comment]
Me too

Javier Munoz Vidal
javier.munoz.vidal@gmail.com

**Comment by paolafer** [comment]
PR #196 addresses this issue with a proposal, to be discussed. Please, have a look at the code, whenever you have a chance.

**Comment by paolafer** [comment]
This issue is being addressed in PR #222.
