### ISSUE TITLE
Build fails with Geant4 10.7

### ISSUE THREAD

**Issue by jmalbos** [next-exp/nexus#57]
Geant4 10.7: https://geant4.web.cern.ch/node/1914

**Comment by jmalbos** [comment]
https://geant4-forum.web.cern.ch/t/10-7-geant4-config-problem-with-includedirs/4032

**Comment by jacg** [comment]
Does this mean that 

1. G4 made a release with a misconfigured configuration tool that they distribute with their own code (`geant4-config`),
2. They have known about the problem and the solution for over a month, and
3. they still haven't fixed it?

The mind boggles.

Point 1 really makes you wonder about their testing procedure.
Point 3 really makes you wonder ...

I infer that this only affects those who compile G4 in one specific way, out of a number of possible ones. One way or another, the geant4 10.7 Nix package doesn't suffer from this problem.

**Comment by jmalbos** [comment]
> I infer that this only affects those who compile G4 in one specific way, out of a number of possible ones. One way or another, the geant4 10.7 Nix package doesn't suffer from this problem.

Hard to say, as I don't know what nix does to build Geant4, but on my Mac I'm using the default options. The building errors, by the way, appear with both SCons and CMake.

**Comment by jacg** [comment]
And do you have a simple recipe (say a shell script that I could paste into a Mac terminal) that summarizes how to install Geant4 on a Mac?

> The building errors, by the way, appear with both SCons and CMake.

Do these appear when you build G4, or when you build Nexus?

**Comment by paolafer** [comment]
> And do you have a simple recipe (say a shell script that I could paste into a Mac terminal) that summarizes how to install Geant4 on a Mac?

See, for instance, the [wiki](https://github.com/next-exp/nexus/wiki/GEANT4-installation).

**Comment by jmalbos** [comment]
```
export G4SRC=/path/to/geant4/source
export G4BUILD=/path/to/geant4/build

cd $G4BUILD
cmake -DGEANT4_INSTALL_DATA=ON -DGEANT4_USE_OPENGL_X11=ON -DCMAKE_INSTALL_PREFIX=$G4SRC $G4SRC
cmake --build . -j N
```
